# Change these first
owner: ASchmidt1024 # Your GitHub organization or username, where this repository lives
repo: uptime-akjs # The name of this repository

sites:
  - name: akjs.io
    url: https://akjs.io
  - name: xrm.rocks
    url: https://xmr.rocks
  - name: pmnr.xrm.rocks
    url: https://pmnr.xmr.rocks
  - name: lookrativ.de
    url: https://lookrativ.de
  - name: kunst-kasten.de
    url: https://kunst-kasten.de
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime-akjs
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime AKJS
  introTitle: "**Uptime** monitor and status page for AKJS websites"
  introMessage: Status page with **real-time** data
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
